# Generated by Django 6.0.2 on 2026-02-24 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspecciones.institucion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspecciones.institucion')),
            ],
        ),
        migrations.CreateModel(
            name='InspeccionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('firma_jefe', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('firma_verificacion', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('bloqueado', models.BooleanField(default=False)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspecciones.institucion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspecciones.servicio')),
            ],
        ),
    ]
