# Generated by Django 6.0.2 on 2026-03-01 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0002_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Administrador'), ('ADMIN_CLINICA', 'Administrador Clínica'), ('BIOMEDICO', 'Biomédico')], default='BIOMEDICO', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspecciones.institucion'),
        ),
    ]
