# Generated by Django 6.0.2 on 2026-03-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0003_perfilusuario_rol_alter_perfilusuario_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Administrador'), ('ADMIN_CLINICA', 'Administrador Clínica'), ('BIOMEDICO', 'Biomédico')], default='BIOMEDICO', max_length=20),
        ),
    ]
