# Generated by Django 6.0.6 on 2026-06-11 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0004_alter_perfilusuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='FallaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], default='BUENO', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('requiere_intervencion', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspecciones.equipo')),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallas', to='inspecciones.inspecciondiaria')),
            ],
        ),
    ]
