# Generated by Django 6.0.6 on 2026-06-11 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0005_fallaequipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='institucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspecciones.institucion'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('ADMIN_CLINICA', 'Admin Clínica'), ('BIOMEDICO', 'Biomédico'), ('AUDITOR', 'Auditor')], max_length=20),
        ),
    ]
