# Generated by Django 6.0.6 on 2026-06-11 15:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0006_alter_perfilusuario_institucion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspecciondiaria',
            name='bloqueado',
        ),
        migrations.RemoveField(
            model_name='inspecciondiaria',
            name='consecutivo',
        ),
        migrations.RemoveField(
            model_name='inspecciondiaria',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='inspecciondiaria',
            name='firma_jefe',
        ),
        migrations.RemoveField(
            model_name='inspecciondiaria',
            name='firma_verificacion',
        ),
        migrations.RemoveField(
            model_name='inspecciondiaria',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='inspecciondiaria',
            name='pdf',
        ),
        migrations.AddField(
            model_name='inspecciondiaria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspecciondiaria',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspecciondiaria',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='inspecciondiaria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
