# Generated by Django 6.0.6 on 2026-06-11 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0008_inspecciondiaria_consecutivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspecciondiaria',
            name='firma_jefe',
        ),
        migrations.RemoveField(
            model_name='inspecciondiaria',
            name='firma_verificacion',
        ),
        migrations.RemoveField(
            model_name='inspecciondiaria',
            name='pdf',
        ),
        migrations.AddField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('OPERATIVO', 'Operativo'), ('FALLA', 'Falla')], default='OPERATIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspecciondiaria',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspecciones.institucion'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('ADMIN_CLINICA', 'Admin Clínica'), ('BIOMEDICO', 'Biomédico')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='inspecciones.institucion'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='FallaEquipo',
        ),
    ]
